I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script
    player "You've created a new Ren'Py game."
Exception: Sayer 'player' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script
    player "You've created a new Ren'Py game."
  File "C:\Users\Skranbets\Downloads\renpy-7.3.0-sdk\renpy\ast.py", line 676, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Skranbets\Downloads\renpy-7.3.0-sdk\renpy\ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'player' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.0.271
Detective Almonds 1.0
Mon Jun 24 10:23:48 2019
